storage:
  postgres:
    postgres_url:
      env: DAGSTER_PG_URL

scheduler:
  module: dagster._core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster._core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster._core.launcher.default_run_launcher
  class: DefaultRunLauncher
