storage:
  postgres:
    postgres_url: "postgresql://iceberg:iceberg123@postgres:5432/dagster"

scheduler:
  module: dagster._core.scheduler.daemon
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster._core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster._core.launcher.default_run_launcher
